import {test,expect} from '@playwright/test';

test('responsive dashboard and auto-closing sidebar preserve typography',async({page,baseURL})=>{
 const headers={Origin:new URL(baseURL!).origin};
 const response=await page.request.post('/api/v1/auth/register',{headers,data:{name:'Layout reviewer',email:`layout-${Date.now()}@example.invalid`,password:'Layout-test-12345'}});
 expect(response.status()).toBe(201);
 const farm=await page.request.post('/api/v1/farms',{headers,data:{name:'Al-Noor Dairy Farm',city:'Lahore',currency:'PKR'}});
 expect(farm.status()).toBe(201);
 await page.setViewportSize({width:1440,height:1000});
 await page.goto('/dashboard?farm='+(await farm.json()).id);
 const sidebar=page.getByRole('complementary',{name:'Farm navigation'});
 await expect(sidebar).toBeHidden();
 await expect(page.locator('.ov-kpis')).toBeVisible();
 expect(await page.evaluate(()=>getComputedStyle(document.body).fontFamily)).toContain('DM Sans');
 await page.screenshot({path:'test-results/dashboard-desktop.png',fullPage:true});
 await expect(page.getByText('Organization and farm setup',{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Toggle menu',exact:true}).click();
 await expect(sidebar).toBeVisible();
 await expect(page.locator('.menu-btn .lucide-x')).toHaveCount(0);
 await expect(page.locator('.farm-menu-overlay')).toBeHidden();
 await page.screenshot({path:'test-results/dashboard-desktop-sidebar.png',fullPage:true});
 await sidebar.getByRole('button',{name:'Settings',exact:true}).click();
 await expect(sidebar).toBeHidden();
 await page.getByRole('button',{name:'Dairy Farm',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Dairy Farm',exact:true})).toBeVisible();
 await expect(page.locator('.dairy-farm-card')).toContainText('Al-Noor Dairy Farm');
 await page.getByRole('button',{name:'Edit farm details',exact:true}).click();
 await page.getByLabel('Address',{exact:true}).fill('12 Farm Road');
 await page.getByLabel('Email',{exact:true}).fill('farm@example.invalid');
 await page.getByLabel('Phone',{exact:true}).fill('+92 300 1234567');
 await page.getByRole('button',{name:'Save farm details',exact:true}).click();
 await expect(page.locator('.dairy-farm-card')).toContainText('12 Farm Road');
 const saved=(await (await page.request.get('/api/v1/farms')).json())[0];
 expect(saved.email).toBe('farm@example.invalid');
 expect(saved.address).toBe('12 Farm Road');
 expect((await page.request.put('/api/v1/farms/'+saved.id,{headers,data:{...saved,version:saved.version-1}})).status()).toBe(409);
 await page.getByRole('button',{name:'Toggle menu',exact:true}).click();
 await sidebar.getByRole('button',{name:'Animals',exact:true}).click();
 await expect(sidebar).toBeHidden();
 await expect(page.getByRole('heading',{name:'Animals',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Toggle menu',exact:true}).click();
 await sidebar.getByRole('button',{name:'Overview',exact:true}).click();
 await expect(sidebar).toBeHidden();
 for(const width of [1024,768,390,320]){
  await page.setViewportSize({width,height:900});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
  await page.getByRole('button',{name:'Toggle menu',exact:true}).click();
  await expect(sidebar).toBeVisible();
  await sidebar.getByRole('button',{name:'Overview',exact:true}).click();
  await expect(sidebar).toBeHidden();
 }
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'test-results/dashboard-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Toggle menu',exact:true}).click();
 await page.keyboard.press('Escape');
 await expect(sidebar).toBeHidden();
 await expect(page.getByRole('button',{name:'Toggle menu',exact:true})).toBeFocused();
 await page.getByRole('button',{name:'اردو',exact:true}).click();
 await expect(page.locator('html')).toHaveAttribute('dir','rtl');
 expect(await page.evaluate(()=>getComputedStyle(document.body).fontFamily)).toContain('Noto Sans Arabic');
 await page.getByRole('button',{name:'گہرا تھیم',exact:true}).click();
 await page.getByRole('button',{name:'مینو کھولیں / بند کریں',exact:true}).click();
 await expect(page.locator('.farm-sidebar')).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.screenshot({path:'test-results/dashboard-urdu-drawer.png',fullPage:true});
});
