'use client';
import Link from 'next/link';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowLeft,ArrowUpRight,Eye,EyeOff,Globe2,LockKeyhole,Mail,ShieldCheck,UserRound} from 'lucide-react';
import Brand from './brand';
import {useLanguage} from './language';
export default function AuthForm({register=false}:{register?:boolean}){
 const {ur,t,toggle}=useLanguage(),router=useRouter();
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[step,setStep]=useState<'email'|'password'>('email'),[email,setEmail]=useState(''),[visible,setVisible]=useState(false);
 async function next(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{const r=await fetch('/api/v1/auth/check-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const d=await r.json();if(!r.ok)throw new Error(d.error);if(!d.exists)throw new Error(t('No account exists for this email address.','اس ای میل ایڈریس کا کوئی اکاؤنٹ موجود نہیں۔'));setStep('password')}catch(e){setError(e instanceof Error?e.message:t('Enter a valid email address.','درست ای میل درج کریں۔'))}finally{setBusy(false)}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');const form=new FormData(e.currentTarget);if(register&&!form.get('terms')){setError(t('Accept the Terms and Privacy Policy to continue.','جاری رکھنے کے لیے شرائط اور رازداری کی پالیسی قبول کریں۔'));return}setBusy(true);try{const response=await fetch(`/api/v1/auth/${register?'register':'login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(form))});const data=await response.json();if(!response.ok)throw new Error(data.error);router.push('/dashboard')}catch(e){setError(t(e instanceof Error?e.message:'Unable to connect.','درخواست مکمل نہیں ہو سکی۔'))}finally{setBusy(false)}}
 const IconInput=({kind,name,type='text',readOnly=false,autoFocus=false}:{kind:'user'|'email'|'password';name:string;type?:string;readOnly?:boolean;autoFocus?:boolean})=><span>{kind==='user'?<UserRound size={17}/>:kind==='email'?<Mail size={17}/>:<LockKeyhole size={17}/>}<input name={name} type={kind==='password'?(visible?'text':'password'):type} value={kind==='email'?email:undefined} onChange={kind==='email'?e=>setEmail(e.target.value):undefined} readOnly={readOnly} required minLength={kind==='password'?6:kind==='user'?2:undefined} maxLength={kind==='password'?72:kind==='user'?100:undefined} autoComplete={kind==='email'?'email':kind==='password'?(register?'new-password':'current-password'):'name'} autoFocus={autoFocus}/>{kind==='password'&&<button type="button" className="password-eye" onClick={()=>setVisible(v=>!v)} aria-label={visible?'Hide password':'Show password'}>{visible?<EyeOff size={17}/>:<Eye size={17}/>}</button>}</span>;
 return <main className="auth-page"><aside className="auth-aside"><Brand/><div><span className="eyebrow">YOUR FARM. A CLEARER PICTURE.</span><h1>{t('Good farming starts with a better view.','بہتر فارمنگ کا آغاز بہتر معلومات سے۔')}</h1><p>{t('One home for your farm’s next chapter.','آپ کے فارم کے اگلے سفر کے لیے ایک جگہ۔')}</p></div><small>DAIRYMONITOR.ONLINE</small></aside><section className="auth-main"><Link className="auth-back" href="/"><ArrowLeft size={16}/>Back to site</Link><button className="language auth-language" onClick={toggle}><Globe2 size={16}/>{ur?'English':'اردو'}</button><div className="auth-form"><span className="feature-icon"><ShieldCheck size={25}/></span><h1>{register?t('Create your account.','اپنا اکاؤنٹ بنائیں۔'):t('Welcome back.','خوش آمدید۔')}</h1><p>{!register&&step==='email'?t('Enter your registered email to continue.','جاری رکھنے کے لیے رجسٹرڈ ای میل درج کریں۔'):t('Secure access to your DairyMonitor workspace.','اپنے ڈیری مانیٹر ورک اسپیس تک محفوظ رسائی۔')}</p>{!register&&step==='email'?<form onSubmit={next}><label className="form-field icon-field">Email address<IconInput kind="email" name="email" type="email" autoFocus/></label>{error&&<div className="form-error" role="alert">{error}</div>}<button className="button" disabled={busy}>{busy?'Checking…':'Next'}<ArrowUpRight size={18}/></button></form>:<form onSubmit={submit}>{register&&<label className="form-field icon-field">Full name<IconInput kind="user" name="name"/></label>}<label className="form-field icon-field">Email address<IconInput kind="email" name="email" type="email" readOnly={!register}/></label><label className="form-field icon-field">Password<IconInput kind="password" name="password" autoFocus={!register}/><small>Use at least 6 characters.</small></label>{register&&<label className="terms-check"><input type="checkbox" name="terms" value="accepted" required/><span>I agree to the <Link href="/terms" target="_blank">Terms & Conditions</Link> and <Link href="/privacy" target="_blank">Privacy Policy</Link>.</span></label>}{error&&<div className="form-error" role="alert">{error}</div>}{!register&&<button type="button" className="row-action auth-change-email" onClick={()=>{setStep('email');setError('')}}><ArrowLeft size={14}/>Use another email</button>}<button className="button" disabled={busy}>{busy?'Please wait…':register?'Create account':'Sign in'}<ArrowUpRight size={18}/></button></form>}<p className="auth-bottom">{register?'Already have an account?':'New to DairyMonitor?'} <Link href={register?'/signin':'/register'}>{register?'Sign in':'Get started'}</Link></p></div></section></main>
}
