'use client';
import {useEffect,useState} from 'react';
import {Check,ChevronRight,ListChecks,Pencil,Plus,Trash2,X} from 'lucide-react';
import {api} from './api';
import SearchSelect from './search-select-v2';
export default function DropdownSettings({base,readOnly}:{base:string;readOnly:boolean}){
 const [rows,setRows]=useState<any[]>([]),[key,setKey]=useState(''),[extra,setExtra]=useState(''),[editing,setEditing]=useState(''),[editText,setEditText]=useState(''),[error,setError]=useState(''),[ok,setOk]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api(base+'/dropdowns').then(setRows).catch(e=>setError(e.message))},[base]);
 const current=rows.find(r=>r.module+'.'+r.field===key);const defaultsEditable=current?.module==='inventory'&&current?.field==='unit';
 async function save(values:string[],message='Dropdown choices saved.') {const clean=values.map(v=>v.trim()).filter(Boolean);if(new Set(clean.map(v=>v.toLowerCase())).size!==clean.length){setError('Each choice must be unique.');return}setBusy(true);setError('');setOk('');try{await api(base+'/dropdowns/'+current.module+'/'+current.field,{method:'PUT',body:JSON.stringify({values:clean})});setRows(r=>r.map(x=>x===current?{...x,values:clean}:x));setExtra('');setEditing('');setEditText('');setOk(message)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="dropdown-editor-layout">
  <section className="workspace-panel dropdown-picker-panel"><div className="record-toolbar"><div><h3><ListChecks size={17}/>Dropdown fields</h3><p>Select the record field whose choices you want to manage.</p></div></div><SearchSelect value={key} onChange={e=>{setKey(e.target.value);setError('');setOk('');setEditing('')}}><option value="">Select a dropdown field</option>{rows.map(r=><option key={r.module+'.'+r.field} value={r.module+'.'+r.field}>{r.moduleName} — {r.name}</option>)}</SearchSelect><div className="dropdown-field-list">{rows.map(r=>{const id=r.module+'.'+r.field;return <button type="button" className={key===id?'selected':''} key={id} onClick={()=>{setKey(id);setError('');setOk('');setEditing('')}}><span><strong>{r.name}</strong><small>{r.moduleName} · {r.values.length} choices</small></span><ChevronRight size={14}/></button>})}</div></section>
  <section className="workspace-panel dropdown-choice-panel">{current?<><div className="record-toolbar"><div><h3>{current.name}</h3><p>{current.moduleName} dropdown · {defaultsEditable?'Default units can be renamed.':'Built-in choices are protected.'}</p></div><span className="choice-count">{current.values.length} choices</span></div><div className="dropdown-help"><Check size={15}/><span><strong>How to edit this dropdown</strong><small>{defaultsEditable?'Use the pencil to rename any base unit. Add new units below; only custom units can be removed.':'Add a new choice below. Use the pencil beside a custom choice to rename it, or the trash button to remove it.'}</small></span></div><div className="dropdown-choice-list">{current.values.map((v:string)=>{const builtIn=current.defaults.includes(v);return <div key={v} className="dropdown-choice-row">{editing===v?<><input autoFocus value={editText} maxLength={100} onChange={e=>setEditText(e.target.value)}/><button type="button" className="choice-icon save" disabled={busy||!editText.trim()} aria-label="Save choice" onClick={()=>void save(current.values.map((x:string)=>x===v?editText:x),'Choice renamed.')}><Check size={15}/></button><button type="button" className="choice-icon" aria-label="Cancel editing" onClick={()=>setEditing('')}><X size={15}/></button></>:<><span><strong>{v}</strong><small className={builtIn?'built-in':'custom'}>{builtIn?'Built-in':'Custom'}</small></span>{!readOnly&&(!builtIn||defaultsEditable)&&<div><button type="button" className="choice-icon" aria-label={'Edit '+v} onClick={()=>{setEditing(v);setEditText(v)}}><Pencil size={14}/></button>{!builtIn&&<button type="button" className="choice-icon danger" disabled={busy} aria-label={'Remove '+v} onClick={()=>void save(current.values.filter((x:string)=>x!==v),'Choice removed.')}><Trash2 size={14}/></button>}</div>}</>}</div>})}</div>{!readOnly&&<form className="dropdown-add-form" onSubmit={e=>{e.preventDefault();void save([...current.values,extra],'Choice added.')}}><label className="form-field">New choice<input value={extra} onChange={e=>setExtra(e.target.value)} required maxLength={100} placeholder="Enter a new dropdown option"/></label><button className="button small" disabled={busy||!extra.trim()}><Plus size={15}/>Add choice</button></form>}{error&&<p className="form-error" role="alert">{error}</p>}{ok&&<p className="form-success" role="status">{ok}</p>}</>:<div className="dropdown-empty"><ListChecks size={34}/><h3>Select a dropdown field</h3><p>Choose a field on the left to view, add, rename, or remove its custom choices.</p></div>}</section>
 </div>;
}
