'use client';
import {useCallback,useEffect,useState} from 'react';
import {Milk,PackagePlus,Plus,RefreshCw} from 'lucide-react';
import {api} from './api';
import SearchSelect from './search-select-v2';
import {formatDate} from './date-format';
type Option={id:string;name:string;unit?:string;stock_quantity?:string};
type Kind='sales'|'purchases';
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Karachi'});
export default function FarmTransactions({base,ur,readOnly,currency}:{base:string;ur:boolean;readOnly:boolean;currency:string}){
 const [kind,setKind]=useState<Kind>('sales'),[rows,setRows]=useState<any[]>([]),[buyers,setBuyers]=useState<Option[]>([]),[suppliers,setSuppliers]=useState<Option[]>([]),[items,setItems]=useState<Option[]>([]),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ok,setOk]=useState('');
 const [form,setForm]=useState<Record<string,string>>({date:today(),party:'',item:'',quantity:'',rate:'',payment_status:'Unpaid',reference:'',notes:''});
 const load=useCallback(async()=>{setError('');try{const [data,b,s,i]=await Promise.all([api(base+(kind==='sales'?'/milk-sales':'/inventory-purchases')),api(base+'/options/buyers'),api(base+'/options/suppliers'),api(base+'/stock')]);setRows(data);setBuyers(b);setSuppliers(s);setItems(i)}catch(e){setError((e as Error).message)}},[base,kind]);useEffect(()=>{void load()},[load]);
 function reset(){setForm({date:today(),party:'',item:'',quantity:'',rate:'',payment_status:'Unpaid',reference:'',notes:''});setShow(false)}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setOk('');try{const body=kind==='sales'?{buyer_id:form.party,sale_date:form.date,quantity:form.quantity,rate:form.rate,payment_status:form.payment_status,reference:form.reference,notes:form.notes}:{supplier_id:form.party,item_id:form.item,purchase_date:form.date,quantity:form.quantity,unit_cost:form.rate,payment_status:form.payment_status,reference:form.reference,notes:form.notes};await api(base+(kind==='sales'?'/milk-sales':'/inventory-purchases'),{method:'POST',body:JSON.stringify(body)});reset();setOk(kind==='sales'?'Milk sale recorded.':'Inventory purchase recorded and stock updated.');await load();if(kind==='purchases')window.dispatchEvent(new Event('stock-changed'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const total=(Number(form.quantity)||0)*(Number(form.rate)||0),parties=kind==='sales'?buyers:suppliers;
 return <div className="transaction-page"><div className="module-heading"><div><h2>{ur?'فروخت اور خریداری':'Sales & purchases'}</h2><p>{ur?'دودھ کی فروخت اور انوینٹری کی خریداری مکمل مالی اور اسٹاک اثر کے ساتھ درج کریں۔':'Record milk sales and inventory purchases with financial and stock impact.'}</p></div>{!readOnly&&<button className="button small" onClick={()=>setShow(true)}><Plus size={15}/>{kind==='sales'?(ur?'دودھ فروخت کریں':'Record milk sale'):(ur?'خریداری درج کریں':'Record purchase')}</button>}</div>
 <div className="transaction-tabs"><button className={kind==='sales'?'active':''} onClick={()=>{setKind('sales');reset()}}><Milk size={17}/><span><strong>{ur?'دودھ کی فروخت':'Milk sales'}</strong><small>{ur?'خریدار اور ادائیگی':'Buyer and payment'}</small></span></button><button className={kind==='purchases'?'active':''} onClick={()=>{setKind('purchases');reset()}}><PackagePlus size={17}/><span><strong>{ur?'انوینٹری خریداری':'Inventory purchases'}</strong><small>{ur?'سپلائر اور اسٹاک':'Supplier and stock'}</small></span></button><button className="refresh" aria-label="Refresh" onClick={()=>void load()}><RefreshCw size={15}/></button></div>
 {error&&<div className="form-error" role="alert">{error}</div>}{ok&&<div className="form-success" role="status">{ok}</div>}
 <section className="workspace-panel transaction-list"><div className="record-toolbar"><h3>{kind==='sales'?'Milk sale history':'Inventory purchase history'}</h3><span>{rows.length} records</span></div><div className="records-table-wrap"><table className="records-table"><thead><tr><th>Date</th><th>{kind==='sales'?'Buyer':'Supplier'}</th>{kind==='purchases'&&<th>Item</th>}<th className="num">Quantity</th><th className="num">Rate / unit cost</th><th className="num">Total</th><th>Payment</th><th>Reference</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{formatDate(r.sale_date||r.purchase_date)}</td><td>{r.buyer_name||r.supplier_name}</td>{kind==='purchases'&&<td>{r.item_name} <small>({r.unit})</small></td>}<td className="num">{r.quantity}</td><td className="num">{currency} {r.rate||r.unit_cost}</td><td className="num"><strong>{currency} {r.total}</strong></td><td><span className={'payment-badge '+String(r.payment_status).toLowerCase().replaceAll(' ','-')}>{r.payment_status}</span></td><td>{r.reference||'—'}</td></tr>)}</tbody></table>{!rows.length&&<div className="table-empty"><Milk size={28}/><h3>No transactions yet</h3><p>Use the button above to record the first {kind==='sales'?'milk sale':'inventory purchase'}.</p></div>}</div></section>
 {show&&<div className="modal-backdrop"><section className="record-modal transaction-modal" role="dialog" aria-modal="true"><div className="modal-heading"><h2>{kind==='sales'?'Record milk sale':'Record inventory purchase'}</h2><button className="row-action" onClick={reset} aria-label="Close">✕</button></div><form onSubmit={submit}><div className="fields-grid"><label className="form-field">Date *<input type="date" max={today()} value={form.date} onChange={e=>setForm(v=>({...v,date:e.target.value}))} required/></label><label className="form-field">{kind==='sales'?'Buyer':'Supplier'} *<SearchSelect value={form.party} onChange={e=>setForm(v=>({...v,party:e.target.value}))} required><option value="">Select {kind==='sales'?'buyer':'supplier'}</option>{parties.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</SearchSelect></label>{kind==='purchases'&&<label className="form-field wide">Inventory item *<SearchSelect value={form.item} onChange={e=>setForm(v=>({...v,item:e.target.value}))} required><option value="">Select inventory item</option>{items.map(x=><option key={x.id} value={x.id}>{x.name} — {x.stock_quantity} {x.unit}</option>)}</SearchSelect></label>}<label className="form-field">Quantity {kind==='sales'?'(litres)':''} *<input type="number" min=".001" step=".001" value={form.quantity} onChange={e=>setForm(v=>({...v,quantity:e.target.value}))} required/></label><label className="form-field">{kind==='sales'?'Rate per litre':'Unit cost'} ({currency}) *<input type="number" min="0" step=".01" value={form.rate} onChange={e=>setForm(v=>({...v,rate:e.target.value}))} required/></label><label className="form-field">Payment status<SearchSelect value={form.payment_status} onChange={e=>setForm(v=>({...v,payment_status:e.target.value}))}><option>Unpaid</option><option>Partially paid</option><option>Paid</option></SearchSelect></label><label className="form-field">Reference<input value={form.reference} onChange={e=>setForm(v=>({...v,reference:e.target.value}))} maxLength={100} placeholder="Invoice or receipt no."/></label><label className="form-field wide">Notes<textarea rows={3} value={form.notes} onChange={e=>setForm(v=>({...v,notes:e.target.value}))} maxLength={2000}/></label></div><div className="transaction-total"><span>Transaction total</span><strong>{currency} {total.toFixed(2)}</strong></div>{error&&<div className="form-error" role="alert">{error}</div>}<div className="modal-footer"><button type="button" className="secondary-button" onClick={reset}>Cancel</button><button className="button" disabled={busy}>{busy?'Saving…':kind==='sales'?'Save milk sale':'Save purchase & add stock'}</button></div></form></section></div>}
 </div>;
}
