'use client';
import {CalendarDays,ChevronLeft,ChevronRight,GripVertical,Pencil,Plus} from 'lucide-react';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {api} from './api';
import SearchSelect from './search-select-v2';
import TaskFollowups from './task-followups-v2';
import {formatDate} from './date-format';
type EventRow={id:string;date:string;title:string;type:string;priority?:string;status?:string};
type StaffRow={id:string;name:string;position?:string};
type View='today'|'week'|'month'|'year';
const iso=(d:Date)=>d.toLocaleDateString('en-CA');
export default function FarmCalendarRedesign({base,ur}:{base:string;ur:boolean}){
 const [anchor,setAnchor]=useState(new Date()),[view,setView]=useState<View>('month'),[events,setEvents]=useState<EventRow[]>([]),[editing,setEditing]=useState<EventRow|null>(null),[creating,setCreating]=useState(false),[staff,setStaff]=useState<StaffRow[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[canEdit,setCanEdit]=useState(false);
 const range=useMemo(()=>{if(view==='today')return[anchor,anchor];if(view==='week'){const a=new Date(anchor);a.setDate(a.getDate()-a.getDay());const b=new Date(a);b.setDate(a.getDate()+6);return[a,b]}if(view==='year')return[new Date(anchor.getFullYear(),0,1),new Date(anchor.getFullYear(),11,31)];return[new Date(anchor.getFullYear(),anchor.getMonth(),1),new Date(anchor.getFullYear(),anchor.getMonth()+1,0)]},[anchor,view]);
 const load=useCallback(()=>api(`${base}/calendar?from=${iso(range[0])}&to=${iso(range[1])}`).then(setEvents).catch(e=>setError(e.message)),[base,range]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{api(base+'/access').then(a=>setCanEdit(a.role==='OWNER'||a.permissions?.tasks==='write')).catch(()=>setCanEdit(false))},[base]);useEffect(()=>{if(canEdit)api(base+'/options/staff').then(setStaff).catch(e=>setError(e.message))},[base,canEdit]);
 const days=useMemo(()=>{const out:(Date|null)[]=[];if(view==='month')for(let i=0;i<range[0].getDay();i++)out.push(null);for(let d=new Date(range[0]);d<=range[1];d.setDate(d.getDate()+1))out.push(new Date(d));return out},[range,view]);
 function move(delta:number){const d=new Date(anchor);view==='year'?d.setFullYear(d.getFullYear()+delta):view==='month'?d.setMonth(d.getMonth()+delta):d.setDate(d.getDate()+delta*(view==='week'?7:1));setAnchor(d)}
 async function update(task:EventRow,date:string,extra:Partial<EventRow>={}){if(!canEdit||task.type!=='Task')return;setBusy(true);setError('');try{await api(base+'/calendar/tasks/'+task.id,{method:'PATCH',body:JSON.stringify({date,title:extra.title,priority:extra.priority,status:extra.status})});setEditing(null);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function createTask(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=Object.fromEntries(new FormData(e.currentTarget));try{await api(base+'/records/tasks',{method:'POST',body:JSON.stringify(form)});setCreating(false);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const periodLabel=view==='today'?formatDate(iso(anchor)):view==='week'?`${formatDate(iso(range[0]))} – ${formatDate(iso(range[1]))}`:view==='year'?String(anchor.getFullYear()):anchor.toLocaleDateString(undefined,{month:'long',year:'numeric'});
 const names:Record<View,[string,string]>={today:['Today','آج'],week:['Week','ہفتہ'],month:['Month','مہینہ'],year:['Year','سال']};
 const eventCard=(item:EventRow)=><button key={item.type+item.id} type="button" draggable={canEdit&&item.type==='Task'} onDragStart={e=>e.dataTransfer.setData('text/task-id',item.id)} onClick={()=>item.type==='Task'&&canEdit&&setEditing(item)} className={`calendar-event ${item.type.toLowerCase()}${item.priority?` priority-${item.priority.toLowerCase()}`:''}${item.status?` status-${item.status.toLowerCase().replaceAll(' ','-')}`:''}`}>{item.type==='Task'&&canEdit&&<GripVertical size={13}/>}<span>{item.title}</span><small>{item.type}</small></button>;
 return <div className="app-view calendar-page">
  <section className="calendar-hero"><span className="calendar-title-icon"><CalendarDays/></span><div><h2>{ur?'فارم کیلنڈر':'Farm operations calendar'}</h2><p>{ur?'ٹاسک کھینچ کر نئی تاریخ پر چھوڑیں، یا موبائل پر ٹاسک کو چھو کر ترمیم کریں۔':'Drag tasks to a new date, or tap a task to edit it on mobile.'}</p></div></section>
  <nav className="calendar-toolbar" aria-label={ur?'کیلنڈر کنٹرولز':'Calendar controls'}><div className="calendar-views">{(Object.keys(names) as View[]).map(item=><button type="button" key={item} className={view===item?'active':''} onClick={()=>setView(item)}>{names[item][ur?1:0]}</button>)}</div><div className="calendar-nav"><button type="button" onClick={()=>move(-1)} aria-label={ur?'پچھلی مدت':'Previous period'}><ChevronLeft/></button><strong>{periodLabel}</strong><button type="button" onClick={()=>move(1)} aria-label={ur?'اگلی مدت':'Next period'}><ChevronRight/></button></div>{canEdit&&<button className="calendar-add" type="button" onClick={()=>setCreating(true)}><Plus size={16}/>{ur?'کام شامل کریں':'Add task'}</button>}</nav>
  {error&&<div className="form-error" role="alert">{error}</div>}
  {view==='year'?<div className="year-grid">{Array.from({length:12},(_,month)=>{const items=events.filter(e=>new Date(e.date).getMonth()===month);return <article className="year-month" key={month}><button type="button" className="year-month-open" onClick={()=>{setAnchor(new Date(anchor.getFullYear(),month,1));setView('month')}}><strong>{new Date(anchor.getFullYear(),month,1).toLocaleDateString(undefined,{month:'long'})}</strong><span>{items.length} {ur?'منصوبہ بند اندراجات':'planned items'}</span></button><div className="year-month-events">{items.slice(0,3).map(eventCard)}</div></article>})}</div>:<div className={`calendar-grid ${view}-view`}>{view!=='today'&&['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=><div className="calendar-weekday" key={day}>{day}</div>)}{days.map((day,index)=><div className={`calendar-day${day&&iso(day)===iso(new Date())?' today':''}`} key={index} onDragOver={e=>{if(canEdit)e.preventDefault()}} onDrop={e=>{const id=e.dataTransfer.getData('text/task-id'),task=events.find(x=>x.id===id&&x.type==='Task');if(day&&task)void update(task,iso(day))}}>{day&&<><span>{view==='today'?day.toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'}):day.getDate()}</span>{events.filter(e=>e.date.slice(0,10)===iso(day)).map(eventCard)}</>}</div>)}</div>}
  {editing&&<div className="modal-backdrop"><form className="record-modal" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void update(editing,String(f.get('date')),{title:String(f.get('title')),priority:String(f.get('priority')),status:String(f.get('status'))})}}><div className="modal-heading"><h2><Pencil size={17}/>{ur?'کام میں ترمیم':'Edit task'}</h2><button type="button" className="row-action" onClick={()=>setEditing(null)}>{ur?'بند کریں':'Close'}</button></div><TaskFields ur={ur} task={editing}/><TaskFollowups base={base} taskId={editing.id} ur={ur}/><div className="modal-footer"><button type="button" className="secondary-button" onClick={()=>setEditing(null)}>{ur?'منسوخ':'Cancel'}</button><button className="button" disabled={busy}>{ur?'کام محفوظ کریں':'Save task'}</button></div></form></div>}
  {creating&&<div className="modal-backdrop"><form className="record-modal" onSubmit={createTask}><div className="modal-heading"><h2><Plus size={18}/>{ur?'کیلنڈر میں کام شامل کریں':'Add task to calendar'}</h2><button type="button" className="row-action" onClick={()=>setCreating(false)}>{ur?'بند کریں':'Close'}</button></div><div className="fields-grid"><label className="form-field wide">{ur?'کام':'Task'} *<input name="title" required maxLength={200}/></label><label className="form-field">{ur?'تاریخ':'Date'} *<input name="date" type="date" defaultValue={iso(anchor)} required/></label><label className="form-field">{ur?'ذمہ دار':'Assigned to'} *<SearchSelect name="assignee" required><option value="">{ur?'عملہ منتخب کریں':'Select staff'}</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}{s.position?` · ${s.position}`:''}</option>)}</SearchSelect></label><label className="form-field">{ur?'ترجیح':'Priority'}<SearchSelect name="priority" defaultValue="Normal"><option>Normal</option><option>High</option><option>Urgent</option></SearchSelect></label><label className="form-field">{ur?'حالت':'Status'}<SearchSelect name="status" defaultValue="Assigned"><option>Assigned</option><option>In progress</option><option>Completed</option><option>Verified</option></SearchSelect></label><label className="form-field wide">{ur?'نوٹس':'Notes'}<textarea name="notes" rows={3} maxLength={4000}/></label></div><div className="modal-footer"><button type="button" className="secondary-button" onClick={()=>setCreating(false)}>{ur?'منسوخ':'Cancel'}</button><button className="button" disabled={busy}>{busy?(ur?'محفوظ ہو رہا ہے…':'Saving…'):(ur?'کام محفوظ کریں':'Save task')}</button></div></form></div>}
 </div>
}
function TaskFields({ur,task}:{ur:boolean;task:EventRow}){return <div className="fields-grid"><label className="form-field wide">{ur?'کام':'Task'}<input name="title" defaultValue={task.title} required/></label><label className="form-field">{ur?'تاریخ':'Date'}<input name="date" type="date" defaultValue={task.date.slice(0,10)} required/></label><label className="form-field">{ur?'ترجیح':'Priority'}<SearchSelect name="priority" defaultValue={task.priority||'Normal'}><option>Normal</option><option>High</option><option>Urgent</option></SearchSelect></label><label className="form-field">{ur?'حالت':'Status'}<SearchSelect name="status" defaultValue={task.status||'Assigned'}><option>Assigned</option><option>In progress</option><option>Completed</option><option>Verified</option></SearchSelect></label></div>}
