'use client';
import {useEffect,useState} from 'react';
import {Activity,ArrowUpRight,CalendarDays,ClipboardList,HeartPulse,Leaf,Milk,Plus,Rss,Sparkles,Syringe,Users} from 'lucide-react';
import {api} from './api';
import MilkProductionGraph from './milk-production-graph';
import {formatDate} from './date-format';

export default function OverviewRedesign({base,ur,select,name}:{base:string;ur:boolean;select:(v:string)=>void;name:string}){
 const [data,setData]=useState<any>(null);const [error,setError]=useState('');
 useEffect(()=>{api(base+'/summary').then(setData).catch(e=>setError(e.message))},[base]);
 if(error)return <div role="alert" className="form-error">{error}</div>;
 if(!data)return <div className="overview-loader" role="status"><span className="loader-ring"/>{ur?'جائزہ لوڈ ہو رہا ہے…':'Loading farm overview…'}</div>;
 const today=Number(data.milk.today||0),yesterday=Number(data.milk.yesterday||0);const delta=yesterday?((today-yesterday)/yesterday)*100:null;
 const trend=(data.trend||[]);const values=trend.map((r:any)=>Number(r.quantity));
 const recent=values.slice(-7).reduce((a:number,b:number)=>a+b,0),prior=values.slice(-14,-7).reduce((a:number,b:number)=>a+b,0);const weekly=prior?((recent-prior)/prior)*100:delta;
 const hour=new Date().getHours();const greeting=ur?(hour<12?'صبح بخیر':hour<17?'دوپہر بخیر':'شام بخیر'):(hour<12?'Good morning':hour<17?'Good afternoon':'Good evening');
 const message=delta==null?(ur?'آج کا دودھ ریکارڈ کریں اور پیداوار دیکھیں۔':'Record today’s milk to start tracking yield.'):(delta>=0?(ur?`${name} کی پیداوار کل سے ${Math.abs(delta).toFixed(1)}% زیادہ ہے۔`:`${name} is tracking ${Math.abs(delta).toFixed(1)}% above yesterday’s yield.`):(ur?`آج کی پیداوار کل سے ${Math.abs(delta).toFixed(1)}% کم ہے۔`:`Today’s yield is ${Math.abs(delta).toFixed(1)}% below yesterday.`));
 const todayDate=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Karachi'});
 return <div className="ov-page ov-redesign">
  <section className="ov-banner"><div className="ov-banner-text"><div className="banner-chip"><Sparkles size={13}/>{ur?'فارم کی تازہ صورتحال':'Live farm pulse'}</div><div className="k"><Activity size={15}/>{greeting}</div><div className="v">{message}</div></div><div className="banner-trend"><span className="trend-ring">{weekly==null?'—':`${weekly>=0?'+':''}${weekly.toFixed(0)}%`}</span><span><small>{ur?'۷ دن کا رجحان':'7-day trend'}</small><strong>{weekly==null?(ur?'ریکارڈ درکار':'More data needed'):`${weekly>=0?'+':''}${weekly.toFixed(1)}% ${ur?'اوسط پیداوار':'average yield'}`}</strong></span></div></section>
  <header className="ov-page-head"><div><div className="ov-eyebrow"><CalendarDays size={13}/>{formatDate(todayDate)}</div><div className="ov-title">{ur?'فارم کا جائزہ':'Farm overview'}</div><div className="ov-sub">{ur?'آپ کے محفوظ کردہ ریکارڈ سے تازہ صورتحال۔ تاریخیں پاکستان کے وقت کے مطابق ہیں۔':'Live figures from your saved farm records. Dates use Pakistan time.'}</div></div><button className="ov-btn" onClick={()=>select('milk')}><Plus size={16}/>{ur?'دودھ درج کریں':'Record milk'}</button></header>
  <div className="ov-kpis">{[
   [ur?'فعال جانور':'Active animals',data.herd.total,'',Users,ur?'موجودہ ریوڑ':'Current herd',''],
   [ur?'دودھ دینے والے':'Lactating animals',data.herd.lactating,'',Milk,ur?'فعال پیداوار':'In production',''],
   [ur?'آج کا دودھ':'Today’s milk',today,'L',Milk,delta==null?(ur?'گزشتہ ڈیٹا نہیں':'No prior data'):`${delta>=0?'↑':'↓'} ${Math.abs(delta).toFixed(1)}% ${ur?'کل کے مقابلے':'vs yesterday'}`,'amber'],
   [ur?'کل کا دودھ':'Yesterday’s milk',yesterday,'L',Activity,ur?'گزشتہ مکمل دن':'Previous full day','']
  ].map(([title,value,unit,Icon,note,tone]:any,index:number)=><article className={`ov-kpi ${tone} tone-${index+1}`} key={title}><div className="ov-kpi-top"><span>{title}</span><span className={`ov-kpi-icon ${tone}`}><Icon size={17}/></span></div><div className="ov-kpi-value">{value}<span className="unit">{unit}</span></div><span className={`ov-delta ${delta!=null&&delta<0&&title===(ur?'آج کا دودھ':'Today’s milk')?'down':''}`}>{note}</span></article>)}</div>
  <div className="ov-grid"><section className="ov-card milk-chart-card"><div className="ov-card-head"><div><div className="ov-card-title">{ur?'دودھ کی پیداوار':'Milk production'}</div><small>{ur?'روزانہ، ہفتہ وار، ماہانہ اور سالانہ رجحان':'Explore daily, weekly, monthly and yearly yield'}</small></div><span className="chart-legend"><i/>{ur?'محفوظ ریکارڈ':'Saved records'}</span></div><MilkProductionGraph trend={trend} ur={ur}/></section>
  <section className="ov-card reminders-card"><div className="ov-card-head"><div><div className="ov-card-title">{ur?'آنے والے کام اور یاد دہانیاں':'Upcoming work & reminders'}</div><small>{data.due.length} {ur?'آئٹمز توجہ طلب ہیں':'items need attention'}</small></div><button className="card-link" type="button" onClick={()=>select('calendar')}>{ur?'کیلنڈر':'Calendar'}<ArrowUpRight size={14}/></button></div>{data.due.length?data.due.slice(0,5).map((r:any)=>{const overdue=String(r.date).slice(0,10)<=todayDate;const ReminderIcon=r.kind==='Vaccination'?Syringe:r.kind==='Task'?ClipboardList:HeartPulse;return <button type="button" className={`ov-reminder ${overdue?'urgent':''}`} key={`${r.kind}-${r.id}`} onClick={()=>select('calendar')}><span className="reminder-icon"><ReminderIcon size={16}/></span><div><div className="ov-rem-title">{r.title}{r.animal?` · ${r.animal}`:''}</div><div className="ov-rem-date">{formatDate(r.date)} · {r.kind}</div></div><span className="reminder-badge">{overdue?(ur?'فوری':'Due'):(ur?'آنے والا':'Upcoming')}</span></button>}):<div className="ov-empty">{ur?'کوئی یاد دہانی نہیں':'No upcoming reminders'}</div>}</section></div>
  <section className="quick-section"><div className="quick-head"><div><div className="ov-card-title">{ur?'فوری رسائی':'Quick access'}</div><small>{ur?'روزمرہ فارم کے کام':'Everyday farm operations'}</small></div></div><div className="ov-actions">{[[Users,ur?'جانور':'Animals',ur?'ریوڑ کا ریکارڈ':'Herd records','animals',''],[HeartPulse,ur?'صحت اور علاج':'Health & treatments',ur?'نگہداشت اور علاج':'Care and treatment','health','purple'],[Leaf,ur?'خوراک اور ذخیرہ':'Feed & inventory',ur?'اسٹاک اور استعمال':'Stock and usage','inventory','amber'],[Rss,ur?'دودھ کے خریدار':'Milk buyers',ur?'فروخت اور ادائیگی':'Sales and payments','buyers','blue']].map(([Icon,title,desc,key,tone]:any)=><button className={`ov-qa ${tone}`} key={key} onClick={()=>select(key)}><span><Icon/></span><div><em>{title}</em><small>{desc}</small></div><ArrowUpRight className="qa-arrow" size={15}/></button>)}</div></section>
 </div>
}
