'use client';
import {Children,isValidElement,useEffect,useId,useRef,useState,type SelectHTMLAttributes,type ReactElement,type ChangeEvent} from 'react';
import {createPortal} from 'react-dom';
import {ChevronDown,Search} from 'lucide-react';
type Props=SelectHTMLAttributes<HTMLSelectElement>&{onSearch?:(query:string)=>void};
export default function SearchSelect({children,value,defaultValue,onChange,disabled,required,name,onSearch,...props}:Props){
 const options=Children.toArray(children).flatMap(child=>isValidElement(child)?[child as ReactElement<{value?:string;children?:unknown;disabled?:boolean}>]:[]);
 const text=(input:unknown):string=>Array.isArray(input)?input.map(text).join(''):input==null?'':typeof input==='object'?'':String(input);
 const choices=options.map(option=>({value:String(option.props.value??text(option.props.children)),label:text(option.props.children),disabled:option.props.disabled}));
 const [local,setLocal]=useState(String(defaultValue??choices[0]?.value??'')),selected=String(value??local);const [open,setOpen]=useState(false),[search,setSearch]=useState(''),[active,setActive]=useState(0);
 const trigger=useRef<HTMLButtonElement>(null),panel=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null),id=useId();const [rect,setRect]=useState({top:0,left:0,width:240,maxHeight:320,above:false});
 const filtered=choices.filter(option=>option.label.toLowerCase().includes(search.toLowerCase()));
 function close(){setOpen(false);trigger.current?.focus()}
 function choose(next:string){setLocal(next);onChange?.({target:{value:next,name},currentTarget:{value:next,name}} as ChangeEvent<HTMLSelectElement>);close()}
 useEffect(()=>{if(!open)return;const position=()=>{const box=trigger.current?.getBoundingClientRect();if(!box)return;const height=window.visualViewport?.height||window.innerHeight,width=Math.min(Math.max(box.width,220),window.innerWidth-16),below=height-box.bottom-10,above=box.top-10,opensAbove=below<220&&above>below,maxHeight=Math.max(150,Math.min(330,opensAbove?above:below)),panelHeight=Math.min(panel.current?.scrollHeight||330,maxHeight),top=opensAbove?Math.max(8,box.top-panelHeight-5):box.bottom+5;setRect({top,left:Math.max(8,Math.min(box.left,window.innerWidth-width-8)),width,maxHeight,above:opensAbove})};position();requestAnimationFrame(()=>{position();input.current?.focus()});const outside=(event:PointerEvent)=>{if(!panel.current?.contains(event.target as Node)&&!trigger.current?.contains(event.target as Node))setOpen(false)};document.addEventListener('pointerdown',outside);window.addEventListener('resize',position);window.addEventListener('scroll',position,true);window.visualViewport?.addEventListener('resize',position);window.visualViewport?.addEventListener('scroll',position);return()=>{document.removeEventListener('pointerdown',outside);window.removeEventListener('resize',position);window.removeEventListener('scroll',position,true);window.visualViewport?.removeEventListener('resize',position);window.visualViewport?.removeEventListener('scroll',position)}},[open]);
 return <span className="search-select"><button type="button" ref={trigger} id={props.id} className={'search-select-trigger '+(props.className||'')} role="combobox" aria-label={props['aria-label']} aria-expanded={open} aria-controls={id} aria-haspopup="listbox" disabled={disabled} onClick={()=>{setSearch('');setActive(0);setOpen(state=>!state)}} onKeyDown={event=>{if(event.key==='ArrowDown'){event.preventDefault();setOpen(true)}}}><span className="search-select-value">{choices.find(option=>option.value===selected)?.label||selected||'Select…'}</span><ChevronDown className="search-select-chevron" size={16} aria-hidden="true"/></button><input className="select-validation" tabIndex={-1} aria-hidden="true" name={name} value={selected} required={required} disabled={disabled} onChange={()=>{}} onInvalid={event=>{event.preventDefault();setOpen(true)}}/>
 {open&&createPortal(<div ref={panel} className={`search-select-panel${rect.above?' opens-above':''}`} style={{top:rect.top,left:rect.left,width:rect.width,maxHeight:rect.maxHeight}} onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();close()}if(event.key==='ArrowDown'){event.preventDefault();setActive(index=>Math.min(index+1,filtered.length-1))}if(event.key==='ArrowUp'){event.preventDefault();setActive(index=>Math.max(index-1,0))}if(event.key==='Enter'){event.preventDefault();if(filtered[active]&&!filtered[active].disabled)choose(filtered[active].value)}if(event.key==='Tab')setOpen(false)}}><label className="search-select-search"><Search size={15}/><input ref={input} aria-label="Search options" placeholder="Search options…" value={search} onChange={event=>{setSearch(event.target.value);onSearch?.(event.target.value);setActive(0)}}/></label><div role="listbox" id={id}>{filtered.map((option,index)=><button type="button" role="option" aria-selected={option.value===selected} disabled={option.disabled} key={option.value} className={index===active?'highlight':''} onClick={()=>choose(option.value)}><span>{option.label||'—'}</span>{option.value===selected&&<span aria-hidden="true">✓</span>}</button>)}{!filtered.length&&<p>No matching options</p>}</div></div>,document.body)}</span>
}
