'use client';
import {useEffect,useState} from 'react';
import SearchSelect from './search-select';
import {api} from './api';
type Item={id:string;name:string;category:string;unit:string;stock_quantity:string};
export type Usage={item_id:string;quantity:number};
export function StockUsage({base,value,onChange,locked=false}:{base:string;value:Usage[];onChange:(v:Usage[],names:string)=>void;locked?:boolean}){
 const [items,setItems]=useState<Item[]>([]),[error,setError]=useState('');
 useEffect(()=>{api(base+'/stock').then(r=>setItems(r.filter((x:Item)=>['Medicine','Vaccine'].includes(x.category)))).catch(e=>setError(e.message))},[base]);
 function change(v:Usage[]){onChange(v,v.map(x=>items.find(i=>i.id===x.item_id)?.name||'').filter(Boolean).join(', '))}
 return <fieldset className="stock-usage"><legend>Vaccines / medications used</legend><p>Select one or more stock items and the quantity actually consumed in each base unit.</p>{value.map((v,i)=><div className="stock-usage-row" key={i}><label className="form-field">Stock item<SearchSelect aria-label={'Stock item '+(i+1)} value={v.item_id} required disabled={locked} onChange={e=>change(value.map((x,n)=>n===i?{...x,item_id:e.target.value}:x))}><option value="">Select medication</option>{items.filter(x=>x.id===v.item_id||!value.some(u=>u.item_id===x.id)).map(x=><option key={x.id} value={x.id}>{x.name} — {x.stock_quantity} {x.unit}</option>)}</SearchSelect></label><label className="form-field">Quantity ({items.find(x=>x.id===v.item_id)?.unit||'base unit'})<input aria-label={'Consumed quantity '+(i+1)} type="number" min="0.001" step="0.001" required disabled={locked} value={v.quantity} onChange={e=>change(value.map((x,n)=>n===i?{...x,quantity:Number(e.target.value)}:x))}/></label>{!locked&&<button type="button" className="secondary-button" onClick={()=>change(value.filter((_,n)=>n!==i))}>Remove</button>}</div>)}{!locked&&<button className="secondary-button" type="button" onClick={()=>change([...value,{item_id:'',quantity:1}])}>Add medication / vaccine</button>}{locked&&<p>Consumption is recorded. Use a stock adjustment with a reason to correct inventory.</p>}{error&&<p role="alert">{error}</p>}</fieldset>
}
export default function StockControls({base,readOnly}:{base:string;readOnly:boolean}){
 const [items,setItems]=useState<Item[]>([]),[item,setItem]=useState(''),[rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{api(base+'/stock').then(setItems).catch(e=>setError(e.message))},[base,revision]);
 useEffect(()=>{if(item)api(base+'/stock/'+item+'/movements').then(setRows).catch(e=>setError(e.message));else setRows([])},[base,item,revision]);
 return <section className="workspace-panel stock-panel"><h3>Stock movements</h3><label className="form-field">Inventory item<SearchSelect value={item} onChange={e=>setItem(e.target.value)}><option value="">Select inventory item</option>{items.map(x=><option key={x.id} value={x.id}>{x.name} — {x.stock_quantity} {x.unit}</option>)}</SearchSelect></label>
 {item&&!readOnly&&<form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');try{await api(base+'/stock/'+item+'/movements',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();setRevision(v=>v+1);window.dispatchEvent(new Event('stock-changed'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><div className="fields-grid"><label className="form-field">Movement<SearchSelect name="direction" defaultValue="add"><option value="add">Add stock / purchase</option><option value="consume">Consume / reduce stock</option></SearchSelect></label><label className="form-field">Date<input type="date" name="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label className="form-field">Quantity<input type="number" name="quantity" min=".001" step=".001" required/></label><label className="form-field">Unit cost (additions)<input type="number" name="unit_cost" min="0" step=".000001" defaultValue="0" required/></label><label className="form-field wide">Reason<input name="reason" required minLength={2} maxLength={300}/></label></div><button className="button small" disabled={busy}>Save stock movement</button></form>}
 {error&&<p role="alert" className="form-error">{error}</p>}{item&&<div className="records-table-wrap"><table className="records-table"><thead><tr><th>Date</th><th>Quantity</th><th>Value change</th><th>Reason</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{String(r.date).slice(0,10)}</td><td>{r.quantity}</td><td>{r.value}</td><td>{r.reason}</td></tr>)}</tbody></table>{!rows.length&&<p>No movements yet.</p>}</div>}</section>
}
