'use client';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight,Check,ChevronRight,Milk,HeartPulse,Leaf,ChartNoAxesCombined,ShieldCheck,Globe2,Smartphone,Sparkles,LayoutDashboard,Users,Wallet,CalendarDays,Sun,ChevronDown,Activity,Menu,X} from 'lucide-react';
import {useState} from 'react';
import Brand from '../components/brand';
import AccountNavigation from '../components/account-navigation';
import CookieConsent from '../components/cookie-consent';
import SocialLinks from '../components/social-links';
import {useLanguage} from '../components/language';
export default function Home(){
 const {ur,toggle,t}=useLanguage();const [menu,setMenu]=useState(false);
 const features=[
  [Users,'Know every animal','ہر جانور کو جانیں','A connected record of your herd, from the first day to the next generation.','پہلے دن سے اگلی نسل تک اپنے ریوڑ کا مکمل ریکارڈ۔'],
  [Milk,'Make every litre count','ہر لیٹر کا حساب','Simple milk recording, clear production trends, and a closer look at performance.','دودھ کا آسان اندراج، پیداوار کے رجحانات اور کارکردگی کا جائزہ۔'],
  [HeartPulse,'Stay ahead of care','بہتر دیکھ بھال','Bring health events, vaccinations, and breeding schedules into one view.','صحت، ویکسینیشن اور افزائش کے شیڈول ایک جگہ دیکھیں۔'],
  [Leaf,'Understand your feed','خوراک کو سمجھیں','Connect inventory and consumption to the true cost of feeding your herd.','ذخیرے اور استعمال کو ریوڑ کی خوراک کے اخراجات سے جوڑیں۔'],
  [Wallet,'See the financial picture','مالی صورتحال دیکھیں','Follow sales, expenses, and buyer balances with a clearer view of your margins.','فروخت، اخراجات اور خریداروں کے بقایاجات کی نگرانی کریں۔'],
  [Sparkles,'Turn records into insight','ریکارڈ سے رہنمائی','Ask questions in everyday language and explore evidence from your farm.','آسان زبان میں سوال کریں اور اپنے فارم کے ریکارڈ سے رہنمائی حاصل کریں۔']
 ] as const;
 return <>
 <div className="announcement"><span className="tiny-dot"/>{t('THE CONNECTED DAIRY FARM','ڈیری فارمنگ کا ایک نیا انداز')}<span className="announcement-sep">/</span>{t('Built for Pakistan','ڈیری مانیٹر سے ملیں')}<ArrowUpRight size={13}/></div>
 <header className="site-header"><div className="container header-inner"><Brand/><nav id="site-navigation" className={menu?'main-nav open':'main-nav'}><Link href="/" onClick={()=>setMenu(false)}>{t('Home','ہوم')}</Link><Link href="/benefits" onClick={()=>setMenu(false)}>{t('Benefits','فوائد')}</Link><Link href="/features" onClick={()=>setMenu(false)}>{t('Features','خصوصیات')}</Link><Link href="/pricing" onClick={()=>setMenu(false)}>{t('Pricing','قیمتیں')}</Link><Link href="/blog" onClick={()=>setMenu(false)}>{t('Blog','بلاگ')}</Link><Link href="/contact" onClick={()=>setMenu(false)}>{t('Contact','رابطہ')}</Link></nav><div className="header-actions"><button className="language" onClick={toggle}><Globe2 size={15}/>{ur?'English':'اردو'}</button><AccountNavigation ur={ur}/><button className="mobile-menu" aria-label="Toggle menu" aria-expanded={menu} aria-controls="site-navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></div></header>
 <main>
 <section className="hero container"><div className="hero-copy"><div className="eyebrow"><span className="tiny-dot"/>{t('YOUR FARM. YOUR PEOPLE. ONE WORKSPACE.','آپ کا فارم۔ ایک واضح تصویر۔')}</div><h1>{t('Better insight.','بہتر معلومات۔')}<br/>{t('Healthier herds.','صحت مند ریوڑ۔')}<br/><span>{t('A stronger farm.','ایک بہتر فارم۔')}</span></h1><p className="hero-description">{t('From the first morning milking to the last payment. Bring your animals, your team, and your farm finances into one clear view.','اپنے جانوروں، دودھ اور فارم کے مالی معاملات کو ایک جگہ لائیں۔ بہتر معلومات کے ساتھ اعتماد سے فیصلے کریں۔')}</p><div className="hero-buttons"><Link href="/register" className="button">{t('Start your farm workspace','ڈیری مانیٹر کے ساتھ شروع کریں')}<ArrowUpRight size={18}/></Link><a href="#preview" className="text-button">{t('Explore the platform','پلیٹ فارم دیکھیں')}<ArrowRight size={17}/></a></div><div className="hero-notes"><span><Check size={15}/>{t('Built for cattle & buffalo farms','پاکستان اور دنیا کے لیے')}</span><span><Check size={15}/>{t('English & اردو','اردو اور انگریزی')}</span></div></div>
 <div className="hero-art"><div className="field-photo" role="img" aria-label={t('Dairy cattle grazing on a green pasture','سبز چراگاہ میں گائیں')}><div className="photo-shade"/><span className="photo-label"><span className="tiny-dot"/>{t('GROWING BETTER, TOGETHER','مل کر بہتر ترقی')}</span><div className="photo-bottom"><span>{t('Every animal matters.','فارمنگ سے جڑا ہوا۔')}<br/><strong>{t('Every day counts.','مستقبل کے لیے تیار۔')}</strong></span><span className="circle-arrow"><ArrowUpRight/></span></div></div><div className="floating-card production-card"><span className="icon-box"><Milk size={21}/></span><div><small>{t('Milk production','دودھ کی پیداوار')}</small><strong>1,284 <span>L</span></strong></div><div className="mini-trend"><span>↗ 8.2%</span><svg width="75" height="32" viewBox="0 0 75 32" aria-hidden="true"><path d="M0 28L10 23L20 25L30 15L40 18L50 8L62 11L75 1" fill="none" stroke="currentColor" strokeWidth="2"/></svg></div></div><div className="floating-card insight-float"><span className="spark-icon"><Sparkles size={18}/></span><div><strong>{t('A little insight. A big difference.','چھوٹی معلومات۔ بڑا فرق۔')}</strong><p>{t('Your next decision starts with better data.','آپ کا اگلا فیصلہ بہتر معلومات سے شروع ہوتا ہے۔')}</p><small>{t('Illustrative product preview','مصنوعات کی مثالی جھلک')}</small></div></div></div></section>
 <div className="principles container"><span>{t('MADE FOR THE WAY YOU FARM','آپ کے فارم کے لیے تیار')}</span><div><Globe2/>{t('English & Urdu','اردو اور انگریزی')}</div><div><Smartphone/>{t('Mobile-first experience','موبائل کے لیے آسان')}</div><div><ShieldCheck/>{t('Your own farm workspace','آپ کا ذاتی فارم ورک اسپیس')}</div><div><Leaf/>{t('Cattle & buffalo farms','گائے اور بھینس کے فارم')}</div></div>
 <section className="section platform-section" id="preview"><div className="container"><div className="section-heading"><div><span className="eyebrow">{t('LESS GUESSWORK. MORE CLARITY.','اندازے کم۔ معلومات زیادہ۔')}</span><h2>{t('Your whole farm.','آپ کا پورا فارم۔')}<br/>{t('One connected view.','ایک مربوط منظر۔')}</h2></div><p>{t('From the morning milking to the month-end numbers, see what matters without getting lost in the details.','صبح کے دودھ سے ماہانہ حساب تک، ضروری معلومات ایک جگہ دیکھیں۔')}</p></div>
 <div className="dashboard-preview"><aside className="preview-sidebar"><Brand/><div className="preview-farm"><span>AN</span><div>Al-Noor Dairy<small>Punjab, Pakistan</small></div><ChevronDown size={14}/></div>{[[LayoutDashboard,'Overview','جائزہ'],[Users,'My herd','میرا ریوڑ'],[Milk,'Milk production','دودھ کی پیداوار'],[HeartPulse,'Health & breeding','صحت اور افزائش'],[Leaf,'Feed & inventory','خوراک اور ذخیرہ'],[Wallet,'Finances','مالی معاملات']].map(([Icon,en,urdu],i)=>{const I=Icon as typeof Milk;return <div className={`preview-nav ${i===0?'active':''}`} key={String(en)}><I size={17}/>{t(en as string,urdu as string)}</div>})}<div className="preview-ai"><Sparkles size={17}/>{t('Farm Copilot','فارم کوپائلٹ')}<span>{t('Planned','منصوبہ')}</span></div></aside>
 <div className="preview-main"><div className="preview-top"><span>{t('Farm overview','فارم کا جائزہ')}</span><span className="sample-badge">{t('SAMPLE DATA · PRODUCT PREVIEW','نمونہ ڈیٹا · پلیٹ فارم کی جھلک')}</span></div><div className="preview-greeting"><div><h3>{t('A good day starts with clarity.','اچھے دن کا آغاز واضح معلومات سے۔')} <Sun size={22}/></h3><p>{t('Here’s a little perspective on your farm today.','آج آپ کے فارم کی صورتحال پر ایک نظر۔')}</p></div><span className="preview-date"><CalendarDays size={14}/>24 August</span></div><div className="preview-stats">{[[Users,'Total animals','کل جانور','128','104 lactating'],[Milk,"Today’s milk",'آج کا دودھ','1,284 L','↗ 8.2% vs yesterday'],[Wallet,'Milk sales','دودھ کی فروخت','PKR 269,640','Illustrative daily total'],[HeartPulse,'Need attention','توجہ درکار','03','Review scheduled care']].map(([Icon,en,urdu,val,sub])=>{const I=Icon as typeof Milk;return <div className="preview-stat" key={String(en)}><span>{t(en as string,urdu as string)}<I size={15}/></span><strong>{val as string}</strong><small>{sub as string}</small></div>})}</div><div className="preview-panels"><div className="chart-panel"><div className="panel-title"><strong>{t('Milk production','دودھ کی پیداوار')}</strong><span>{t('Last 7 days','گزشتہ ۷ دن')}</span></div><div className="chart"><div className="chart-labels"><span>1,400</span><span>1,200</span><span>1,000</span></div><svg viewBox="0 0 600 150" role="img" aria-label="Illustrative seven-day milk production trend"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#6f9976" stopOpacity=".3"/><stop offset="1" stopColor="#6f9976" stopOpacity="0"/></linearGradient></defs><path d="M0 25H600M0 75H600M0 125H600" stroke="#e9eee9" strokeDasharray="4 4"/><path d="M0 120C45 120 45 60 100 70S170 100 200 75S260 20 300 42S370 85 400 55S470 10 500 24S560 50 600 14V150H0Z" fill="url(#area)"/><path d="M0 120C45 120 45 60 100 70S170 100 200 75S260 20 300 42S370 85 400 55S470 10 500 24S560 50 600 14" stroke="#39734c" strokeWidth="3" fill="none"/></svg></div><div className="chart-days">{'Mon Tue Wed Thu Fri Sat Sun'.split(' ').map(d=><span key={d}>{d}</span>)}</div></div><div className="daily-insight"><span><Sparkles size={17}/>{t('A closer look','ایک گہری نظر')}</span><h4>{t('Good records lead to better questions.','اچھا ریکارڈ بہتر سوالات کا آغاز ہے۔')}</h4><p>{t('Explore production changes alongside feed and health events. Farm Copilot is on our roadmap.','خوراک اور صحت کے ساتھ پیداوار میں تبدیلی دیکھیں۔ فارم کوپائلٹ جلد شامل ہوگا۔')}</p><a href="#intelligence">{t('Meet your future copilot','اپنے مستقبل کے کوپائلٹ سے ملیں')}<ArrowRight size={14}/></a></div></div></div></div></div></section>
 <section className="section container" id="features"><div className="center-heading"><span className="eyebrow">{t('ONE PLATFORM, FROM THE GROUND UP','ایک پلیٹ فارم، مکمل انتظام')}</span><h2>{t('Built around your everyday.','آپ کے روزمرہ کاموں کے لیے۔')}</h2><p>{t('Manage today’s work. Build a better picture of tomorrow.','آپ کے فارم کو آگے بڑھانے والے کاموں کے لیے ایک واضح منصوبہ۔')}</p></div><div className="feature-grid">{features.map(([Icon,en,urdu,desc,udesc])=><article className="feature-card" key={en}><span className="feature-icon"><Icon size={23}/></span><span className="planned-label">{en==='Turn records into insight'?t('Coming soon','جلد آ رہا ہے'):t('In your workspace','آپ کے ورک اسپیس میں')}</span><h3>{t(en,urdu)}</h3><p>{t(desc,udesc)}</p></article>)}</div></section>
 <section className="container" id="intelligence"><div className="intelligence"><div><span className="eyebrow"><Sparkles size={15}/>{t('INTRODUCING FARM COPILOT · COMING SOON','فارم کوپائلٹ · جلد آ رہا ہے')}</span><h2>{t('Your records have a story.','آپ کے ریکارڈ میں ایک کہانی ہے۔')}<br/>{t('Let’s make sense of it.','آئیے اسے سمجھیں۔')}</h2><p>{t('Ask in your own words. Understand the changes. Know what to look at next. AI assistance grounded in your farm’s records, with you in control.','اپنی زبان میں سوال کریں۔ تبدیلیوں کو سمجھیں۔ اپنے فارم کے ریکارڈ پر مبنی اے آئی کی مدد حاصل کریں، اختیار آپ کے پاس رہے۔')}</p><div className="ai-points"><span><Check size={16}/>{t('Evidence behind every insight','ہر تجزیے کے پیچھے ریکارڈ')}</span><span><Check size={16}/>{t('Your permissions, always respected','آپ کی اجازتوں کا احترام')}</span></div></div><div className="chat-preview"><div className="chat-header"><span className="spark-icon"><Sparkles size={18}/></span><strong>Farm Copilot</strong><span>{t('Concept preview','تصوراتی جھلک')}</span></div><div className="chat-question">{t('Why did milk production change this week?','اس ہفتے دودھ کی پیداوار کیوں بدلی؟')}</div><div className="chat-answer"><Sparkles size={19}/><div>{t('Start with the animals behind the change.','ان جانوروں سے شروع کریں جن کی پیداوار بدلی ہے۔')}<p>{t('I’ll help you compare milk records, feed changes, and recent health events — and highlight missing data before drawing conclusions.','میں دودھ، خوراک اور صحت کے ریکارڈ کا موازنہ کرنے اور نامکمل معلومات کی نشاندہی میں مدد کروں گا۔')}</p><span className="evidence-chip"><Activity size={12}/>{t('Farm data → useful context','فارم کا ڈیٹا ← مفید معلومات')}</span></div></div><div className="chat-foot">{t('Decision support. Always guided by you and your farm professionals.','فیصلوں میں مدد۔ آپ اور آپ کے فارم کے ماہرین کی رہنمائی میں۔')}</div></div></div></section>
 <section className="section container" id="how-it-works"><div className="center-heading"><span className="eyebrow">{t('A SIMPLE BEGINNING','ایک آسان آغاز')}</span><h2>{t('Your next chapter starts here.','آپ کے اگلے سفر کا آغاز یہاں ہے۔')}</h2></div><div className="steps">{[['01','Create your account','اپنا اکاؤنٹ بنائیں','Choose English or Urdu and get your own secure login.','اردو یا انگریزی منتخب کریں اور اپنا اکاؤنٹ بنائیں۔'],['02','Set up your farm','اپنا فارم ترتیب دیں','Add your farm name, location, and preferred currency.','فارم کا نام، مقام اور کرنسی شامل کریں۔'],['03','Grow with the platform','پلیٹ فارم کے ساتھ آگے بڑھیں','Start recording animals, milk, health events, and farm finances.','نئے ماڈیولز کے لیے آپ کا ورک اسپیس تیار ہے۔']].map(([n,en,u,d,ud])=><div className="step" key={n}><span>{n}</span><h3>{t(en,u)}</h3><p>{t(d,ud)}</p></div>)}</div></section>
 <section className="container"><div className="closing-cta"><div><span className="eyebrow">{t('A BETTER VIEW STARTS TODAY','بہتر معلومات کا آغاز آج')}</span><h2>{t('More clarity. More possibility.','زیادہ وضاحت۔ زیادہ امکانات۔')}</h2><p>{t('Make room for a smarter way to manage your farm.','اپنے فارم کے انتظام کے لیے ایک بہتر طریقہ اپنائیں۔')}</p></div><Link className="button cream" href="/register">{t('Create your account','اپنا اکاؤنٹ بنائیں')}<ArrowUpRight size={18}/></Link></div></section>
 <section className="section container benefits-section" id="benefits"><div className="center-heading"><span className="eyebrow">{t('WHY DAIRYMONITOR','ڈیری مانیٹر کیوں')}</span><h2>{t('Less paperwork. Better farm decisions.','کم کاغذی کارروائی۔ بہتر فیصلے۔')}</h2></div><div className="benefit-grid"><article><ShieldCheck/><h3>{t('One reliable record','ایک قابل اعتماد ریکارڈ')}</h3><p>{t('Keep herd, health, stock, people, and financial records connected and permission-controlled.','ریوڑ، صحت، اسٹاک اور مالی ریکارڈ ایک محفوظ جگہ رکھیں۔')}</p></article><article><CalendarDays/><h3>{t('Plan work before it is due','کام وقت سے پہلے منظم کریں')}</h3><p>{t('Use reminders and the farm calendar to stay ahead of tasks, vaccines, and follow-ups.','کام، ویکسین اور فالو اپ کیلنڈر میں دیکھیں۔')}</p></article><article><ChartNoAxesCombined/><h3>{t('See trends, not scattered entries','رجحانات واضح دیکھیں')}</h3><p>{t('Turn everyday records into useful dashboard views and export-ready reports.','روزمرہ ریکارڈ کو ڈیش بورڈ اور رپورٹس میں بدلیں۔')}</p></article></div></section>
 <section className="section container" id="blog"><div className="section-heading"><div><span className="eyebrow">{t('FROM THE FIELD','فارم سے معلومات')}</span><h2>{t('Practical dairy farm guides.','عملی ڈیری فارم رہنمائی۔')}</h2></div><p>{t('Short, useful articles on herd records, milk quality, stock control, and farm teamwork.','ریوڑ، دودھ، اسٹاک اور ٹیم ورک پر مفید مضامین۔')}</p></div><div className="blog-grid">{['Building a dependable animal register','Planning vaccination and medicine stock','Using milk records to spot change'].map((x,i)=><article key={x}><small>{t('GUIDE','رہنمائی')} · 0{i+1}</small><h3>{x}</h3><a href={`mailto:hello@dairymonitor.online?subject=${encodeURIComponent(x)}`}>{t('Request this guide','یہ رہنمائی حاصل کریں')}<ArrowRight size={15}/></a></article>)}</div></section>
 <section className="container contact-panel" id="contact"><div><span className="eyebrow">{t('LET’S TALK','رابطہ کریں')}</span><h2>{t('Questions about your farm setup?','اپنے فارم سیٹ اپ کے بارے میں سوال؟')}</h2><p>{t('Tell us what you manage and we will help you find a practical starting point.','اپنی ضرورت بتائیں، ہم عملی آغاز میں مدد کریں گے۔')}</p></div><a className="button cream" href="mailto:hello@dairymonitor.online">hello@dairymonitor.online<ArrowUpRight size={17}/></a></section>
 </main><footer className="site-footer"><div className="container site-footer-grid"><div><Brand/><p>{t('A connected workspace for healthier herds and stronger dairy farms.','صحت مند ریوڑ اور بہتر ڈیری فارم کے لیے مربوط ورک اسپیس۔')}</p><SocialLinks/></div><div><strong>{t('Explore','دیکھیں')}</strong><Link href="/">{t('Home','ہوم')}</Link><Link href="/benefits">{t('Benefits','فوائد')}</Link><Link href="/features">{t('Features','خصوصیات')}</Link><Link href="/pricing">{t('Pricing','قیمتیں')}</Link></div><div><strong>{t('Resources & legal','وسائل اور قانونی')}</strong><Link href="/blog">{t('Blog','بلاگ')}</Link><Link href="/contact">{t('Contact us','رابطہ')}</Link><Link href="/privacy">{t('Privacy policy','رازداری')}</Link><Link href="/cookies">{t('Cookie policy','کوکی پالیسی')}</Link><Link href="/terms">{t('Terms','شرائط')}</Link></div></div><div className="container site-footer-bottom"><span>© {new Date().getFullYear()} DairyMonitor</span><span>{t('No credit card required · 14-day free trial','کریڈٹ کارڈ درکار نہیں · ۱۴ دن مفت')}</span><button className="language" onClick={toggle}><Globe2 size={15}/>{ur?'English':'اردو'}</button></div></footer>
 <CookieConsent/></>
}
