export type Field={key:string;en:string;ur:string;type:'text'|'date'|'number'|'select'|'textarea'|'animal'|'buyer'|'staff';required?:boolean;options?:string[];min?:number;max?:number;scale?:number};
export type Module={key:string;en:string;ur:string;singular:string;description:string;fields:Field[]};
const field=(key:string,en:string,ur:string,type:Field['type']='text',extra:Partial<Field>={}):Field=>({key,en,ur,type,...extra});
const animal=field('animal_id','Animal','جانور','animal',{required:true});
const date=field('date','Date','تاریخ','date',{required:true});
const notes=field('notes','Notes','نوٹس','textarea');
export const modules:Module[]=[
 {key:'animals',en:'Animals',ur:'جانور',singular:'animal',description:'Animal register, identity, breed and production status.',fields:[field('tag','Tag number','ٹیگ نمبر','text',{required:true}),field('name','Name','نام'),field('species','Species','نوع','select',{required:true,options:['Cattle','Buffalo','Goat','Sheep']}),field('breed','Breed','نسل'),field('sex','Sex','جنس','select',{required:true,options:['Female','Male']}),field('birth_date','Date of birth','پیدائش کی تاریخ','date'),field('stage','Life stage','عمر کا مرحلہ','select',{required:true,options:['Calf','Heifer','Adult']}),field('production_status','Production status','پیداواری حالت','select',{required:true,options:['Lactating','Dry','Not producing']}),field('reproductive_status','Reproductive status','تولیدی حالت','select',{required:true,options:['Unknown','Open','Pregnant']}),field('health_status','Health status','صحت کی حالت','select',{required:true,options:['Healthy','Sick','Under treatment']}),field('disposition','Herd status','ریوڑ کی حالت','select',{required:true,options:['Active','Sold','Dead','Transferred']}),field('location','Shed / pen','شیڈ / باڑا'),field('rfid','RFID','آر ایف آئی ڈی'),field('purchase_date','Purchase date','خریداری کی تاریخ','date'),field('purchase_price','Purchase price','قیمت خرید','number',{min:0,scale:2}),notes]},
 {key:'milk',en:'Milk recording',ur:'دودھ کا ریکارڈ',singular:'milk record',description:'Record animal production by date and milking session.',fields:[animal,date,field('session','Session','وقت','select',{required:true,options:['Morning','Evening','Other']}),field('quantity','Quantity (litres)','مقدار (لیٹر)','number',{required:true,min:0,max:200,scale:3}),field('fat','Fat %','چکنائی ٪','number',{min:0,max:100,scale:2}),field('snf','SNF %','ایس این ایف ٪','number',{min:0,max:100,scale:2}),field('destination','Destination','استعمال','select',{required:true,options:['Tank','Calves','Discarded','Farm use']}),notes]},
 {key:'weights',en:'Weight records',ur:'وزن کا ریکارڈ',singular:'weight record',description:'Track growth and body condition over time.',fields:[animal,date,field('weight','Weight (kg)','وزن (کلو)','number',{required:true,min:0.01,max:3000,scale:2}),field('body_condition','Body condition (1–5)','جسمانی حالت (۱–۵)','number',{min:1,max:5,scale:1}),notes]},
 {key:'health',en:'Health & treatments',ur:'صحت اور علاج',singular:'health record',description:'Record professional observations, treatment and follow-ups.',fields:[animal,date,field('symptoms','Symptoms','علامات','textarea',{required:true}),field('diagnosis','Veterinarian diagnosis','ڈاکٹر کی تشخیص'),field('veterinarian','Veterinarian','ویٹرنری ڈاکٹر'),field('medicine','Medicine','دوا'),field('dose','Prescribed dose / instructions','تجویز کردہ خوراک / ہدایات'),field('end_date','Treatment end date','علاج ختم ہونے کی تاریخ','date'),field('follow_up','Follow-up date','دوبارہ معائنہ','date'),field('milk_withdrawal_until','Milk withdrawal until','دودھ روکنے کی آخری تاریخ','date'),field('meat_withdrawal_until','Meat withdrawal until','گوشت روکنے کی آخری تاریخ','date'),field('status','Status','حالت','select',{required:true,options:['Active','Completed']}),field('cost','Treatment cost (reference only)','علاج کی لاگت (حوالہ)','number',{min:0,scale:2}),notes]},
 {key:'vaccinations',en:'Vaccinations',ur:'ویکسینیشن',singular:'vaccination',description:'Administered vaccines and upcoming due dates.',fields:[animal,date,field('vaccine','Vaccine','ویکسین','text',{required:true}),field('next_due','Next due date','اگلی تاریخ','date'),field('batch','Batch number','بیچ نمبر'),field('veterinarian','Veterinarian','ویٹرنری ڈاکٹر'),field('cost','Cost (reference only)','لاگت (حوالہ)','number',{min:0,scale:2}),notes]},
 {key:'breeding',en:'Breeding',ur:'افزائش',singular:'breeding event',description:'Heat, service, pregnancy checks, dry-off and calving events.',fields:[animal,date,field('event','Event','واقعہ','select',{required:true,options:['Heat','Insemination','Pregnancy check','Dry off','Calving']}),field('result','Result','نتیجہ','select',{options:['Unknown','Positive','Negative','Successful','Unsuccessful']}),field('bull','Bull / semen reference','سانڈ / سیمن حوالہ'),field('technician','Technician','ٹیکنیشن'),field('expected_date','Next check / expected calving','اگلی جانچ / متوقع ولادت','date'),field('calf_tag','Calf tag','بچھڑے کا ٹیگ'),field('cost','Cost (reference only)','لاگت (حوالہ)','number',{min:0,scale:2}),notes]},
 {key:'tasks',en:'Tasks',ur:'کام',singular:'task',description:'Assign daily work and track completion and verification.',fields:[field('title','Task','کام','text',{required:true}),field('date','Due date','مقررہ تاریخ','date',{required:true}),field('assignee','Assigned to','ذمہ دار','staff',{required:true}),field('animal_id','Animal (optional)','جانور (اختیاری)','animal'),field('priority','Priority','ترجیح','select',{required:true,options:['Normal','High','Urgent']}),field('status','Status','حالت','select',{required:true,options:['Assigned','In progress','Completed','Verified']}),notes]},
 {key:'buyers',en:'Milk buyers',ur:'دودھ کے خریدار',singular:'buyer',description:'Buyer contacts, agreed rates and payment terms.',fields:[field('name','Buyer name','خریدار کا نام','text',{required:true}),field('phone','Phone','فون'),field('address','Address','پتہ'),field('rate','Rate per litre','فی لیٹر قیمت','number',{min:0,scale:2}),field('payment_cycle','Payment cycle','ادائیگی کا دورانیہ','select',{options:['Daily','Weekly','Monthly']}),notes]},
 {key:'suppliers',en:'Suppliers',ur:'سپلائرز',singular:'supplier',description:'Supplier contacts and purchasing terms.',fields:[field('name','Supplier name','سپلائر کا نام','text',{required:true}),field('phone','Phone','فون'),field('address','Address','پتہ'),field('products','Products supplied','فراہم کردہ اشیا'),field('payment_terms','Payment terms','ادائیگی کی شرائط'),notes]},
 {key:'staff',en:'Staff',ur:'عملہ',singular:'staff member',description:'Employee records. Employment does not grant account access.',fields:[field('name','Full name','پورا نام','text',{required:true}),field('email','Email','ای میل'),field('phone','Phone','فون'),field('position','Position','عہدہ'),field('joining_date','Joining date','شمولیت کی تاریخ','date'),field('salary','Monthly salary (reference)','ماہانہ تنخواہ (حوالہ)','number',{min:0,scale:2}),field('status','Status','حالت','select',{required:true,options:['Active','Inactive']}),notes]},
 {key:'partners',en:'Partners',ur:'شراکت دار',singular:'partner',description:'Partner directory. Ownership and distributions require separate agreements.',fields:[field('name','Partner name','شراکت دار کا نام','text',{required:true}),field('phone','Phone','فون'),field('investment_date','Agreement date','معاہدے کی تاریخ','date'),field('agreement','Agreement notes','معاہدے کی تفصیل','textarea'),notes]},
 {key:'inventory',en:'Feed & inventory',ur:'خوراک اور ذخیرہ',singular:'stock item',description:'Create items, then record purchases and consumption in Stock movements.',fields:[field('name','Item name','شے کا نام','text',{required:true}),field('category','Category','قسم','select',{required:true,options:['Feed','Medicine','Vaccine','Equipment','Supplies']}),field('unit','Base unit','بنیادی اکائی','select',{required:true,options:['kg','litre','piece','dose']}),field('minimum_stock','Minimum stock','کم از کم ذخیرہ','number',{required:true,min:0,scale:3}),field('storage','Storage location','ذخیرے کا مقام'),notes]}
];
export const getModule=(key:string)=>modules.find(m=>m.key===key);
