'use client';
import {FormEvent,useEffect,useState} from 'react';
import {MessageCircle,Send,Sparkles,X} from 'lucide-react';
import {api} from './api';
type Summary={herd:{total:number;lactating:number;attention:number};milk:{today:string;yesterday:string;month:string};due:{kind:string;title:string;date:string;animal?:string}[]};
type Message={role:'user'|'assistant';text:string};
function answer(question:string,data:Summary){const q=question.toLowerCase(),today=Number(data.milk.today||0),yesterday=Number(data.milk.yesterday||0),change=yesterday?Math.round((today-yesterday)/yesterday*1000)/10:null;if(q.includes('milk')||q.includes('yield')||q.includes('production'))return change===null?`Today’s recorded milk is ${today} L. Add yesterday’s milk records to calculate a reliable comparison.`:`Today’s recorded milk is ${today} L, ${Math.abs(change)}% ${change>=0?'above':'below'} yesterday’s ${yesterday} L. Review animal-level milk, feed, and health records before deciding on a cause.`;if(q.includes('health')||q.includes('attention'))return `${data.herd.attention} of ${data.herd.total} active animals currently need attention. Open Health & treatments to review diagnoses, withdrawal dates, and follow-ups.`;if(q.includes('task')||q.includes('due')||q.includes('plan')){const due=data.due.slice(0,5);return due.length?`${data.due.length} upcoming or overdue items are visible. Next: ${due.map(x=>`${x.title} (${String(x.date).slice(0,10)})`).join('; ')}.`:'There are no upcoming tasks or vaccination reminders in the current summary.'}return `This farm has ${data.herd.total} active animals, including ${data.herd.lactating} lactating animals. Today’s milk is ${today} L and there are ${data.due.length} upcoming or overdue items. Ask about milk, herd health, or planned work for a focused answer.`}
export default function FarmCopilot({base,ur}:{base:string;ur:boolean}){
 const [open,setOpen]=useState(false),[data,setData]=useState<Summary|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[question,setQuestion]=useState(''),[messages,setMessages]=useState<Message[]>([]);
 useEffect(()=>{setData(null);setMessages([]);setError('')},[base]);
 async function ensureData(){if(data)return data;setLoading(true);setError('');try{const next=await api(base+'/summary');setData(next);return next as Summary}catch(e){setError((e as Error).message);return null}finally{setLoading(false)}}
 async function ask(text:string){const clean=text.trim();if(!clean)return;setQuestion('');setMessages(v=>[...v,{role:'user',text:clean}]);const summary=await ensureData();if(summary)setMessages(v=>[...v,{role:'assistant',text:answer(clean,summary)}])}
 function submit(e:FormEvent){e.preventDefault();void ask(question)}
 return <div className="farm-copilot">{open&&<section className="copilot-panel" role="dialog" aria-label={ur?'اے آئی فارم کوپائلٹ':'AI Farm Copilot'}><div className="copilot-head"><span><Sparkles size={18}/><strong>{ur?'اے آئی فارم کوپائلٹ':'AI Farm Copilot'}</strong></span><button type="button" className="row-action" onClick={()=>setOpen(false)} aria-label="Close Copilot"><X size={18}/></button></div><p>{ur?'اپنے موجودہ فارم ریکارڈ کے بارے میں سوال کریں۔':'Ask questions grounded in your current farm records.'}</p><div className="copilot-suggestions">{['How is milk production today?','Which work is due next?','How many animals need attention?'].map(x=><button type="button" className="secondary-button" key={x} onClick={()=>void ask(x)}>{x}</button>)}</div><div className="copilot-messages" aria-live="polite">{messages.length===0&&<div className="copilot-empty"><Sparkles size={24}/><span>{ur?'شروع کرنے کے لیے ایک سوال منتخب کریں۔':'Choose a question or write your own.'}</span></div>}{messages.map((m,i)=><div className={`copilot-message ${m.role}`} key={i}>{m.text}</div>)}{loading&&<div className="copilot-message assistant">Reviewing farm records…</div>}{error&&<div className="form-error" role="alert">{error}</div>}</div><form className="copilot-form" onSubmit={submit}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder={ur?'فارم کے بارے میں پوچھیں…':'Ask about your farm…'} aria-label="Copilot question"/><button type="submit" className="button small" disabled={loading||!question.trim()} aria-label="Send question"><Send size={16}/></button></form><small className="copilot-note">{ur?'ریکارڈ پر مبنی رہنمائی؛ طبی یا مالی پیشہ ورانہ مشورہ نہیں۔':'Record-based decision support, not veterinary or financial advice.'}</small></section>}<button type="button" className="copilot-launch" onClick={()=>setOpen(v=>!v)} aria-expanded={open}><MessageCircle size={20}/><span>{ur?'فارم کوپائلٹ':'AI Farm Copilot'}</span></button></div>;
}

