ALTER TABLE farms ADD COLUMN IF NOT EXISTS address text NOT NULL DEFAULT '';
ALTER TABLE farms ADD COLUMN IF NOT EXISTS email text NOT NULL DEFAULT '';
ALTER TABLE farms ADD COLUMN IF NOT EXISTS phone text NOT NULL DEFAULT '';
ALTER TABLE farms ADD COLUMN IF NOT EXISTS country text NOT NULL DEFAULT '';
ALTER TABLE farms ADD COLUMN IF NOT EXISTS postal_code text NOT NULL DEFAULT '';
ALTER TABLE farms ADD COLUMN IF NOT EXISTS contact_name text NOT NULL DEFAULT '';
ALTER TABLE farms ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;
