'use client';
import Link from 'next/link';
import {ArrowLeft,CheckCircle2,KeyRound,ShieldCheck,UserRound} from 'lucide-react';
import {useEffect,useState} from 'react';
import Brand from '../../components/brand';
import {useLanguage} from '../../components/language';

export default function AccountPage(){
 const {ur,t}=useLanguage();const [user,setUser]=useState({name:'',email:'',two_factor_enabled:false});const [current,setCurrent]=useState(''),[next,setNext]=useState(''),[confirm,setConfirm]=useState('');const [error,setError]=useState(''),[ok,setOk]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch('/api/v1/auth/me').then(async r=>{if(r.status===401){window.location.href='/signin';return null}return r.json()}).then(d=>d&&setUser(d)).catch(()=>setError('Could not load your account.'))},[]);
 async function saveProfile(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setOk('');try{const r=await fetch('/api/v1/auth/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:user.name,two_factor_enabled:user.two_factor_enabled})});const d=await r.json();if(!r.ok)throw new Error(d.error);setUser(d);setOk(t('Profile and security preference saved.','پروفائل اور سیکیورٹی محفوظ ہو گئی۔'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function password(e:React.FormEvent){e.preventDefault();setError('');setOk('');if(next!==confirm){setError(t('Passwords do not match.','پاس ورڈ مماثل نہیں۔'));return}setBusy(true);try{const r=await fetch('/api/v1/auth/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({current_password:current,new_password:next})});const d=await r.json();if(!r.ok)throw new Error(d.error);window.location.href='/signin'}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="account-page"><header className="account-header"><Brand href="/dashboard"/><Link className="secondary-button" href="/dashboard"><ArrowLeft size={16}/>{t('Back to dashboard','ڈیش بورڈ پر واپس')}</Link></header><div className="account-content"><div className="module-heading"><div><h1>{t('Profile & security','پروفائل اور سیکیورٹی')}</h1><p>{t('Manage your profile, password, and two-factor security in one place.','پروفائل، پاس ورڈ اور دو مرحلہ سیکیورٹی ایک جگہ سنبھالیں۔')}</p></div></div>{error&&<div className="form-error" role="alert">{error}</div>}{ok&&<div className="form-success"><CheckCircle2 size={16}/>{ok}</div>}<div className="account-grid"><form className="workspace-panel" onSubmit={saveProfile}><h2><UserRound size={18}/>{t('Profile details','پروفائل کی تفصیل')}</h2><label className="form-field">{t('Full name','پورا نام')}<input value={user.name} onChange={e=>setUser(v=>({...v,name:e.target.value}))} required/></label><label className="form-field">{t('Email','ای میل')}<input value={user.email} disabled/></label><label className="security-switch"><span><ShieldCheck size={18}/><span><strong>{t('Two-factor authentication','دو مرحلہ تصدیق')}</strong><small>{t('Enable or disable the additional account security preference.','اضافی اکاؤنٹ سیکیورٹی فعال یا غیر فعال کریں۔')}</small></span></span><input type="checkbox" checked={user.two_factor_enabled} onChange={e=>setUser(v=>({...v,two_factor_enabled:e.target.checked}))}/></label><button className="button" disabled={busy}>{t('Save profile','پروفائل محفوظ کریں')}</button></form><form className="workspace-panel" onSubmit={password}><h2><KeyRound size={18}/>{t('Change password','پاس ورڈ تبدیل کریں')}</h2><label className="form-field">{t('Current password','موجودہ پاس ورڈ')}<input type="password" value={current} onChange={e=>setCurrent(e.target.value)} required/></label><label className="form-field">{t('New password','نیا پاس ورڈ')}<input type="password" minLength={6} value={next} onChange={e=>setNext(e.target.value)} required/></label><label className="form-field">{t('Confirm new password','نئے پاس ورڈ کی تصدیق')}<input type="password" minLength={6} value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label><button className="button" disabled={busy}>{t('Change password','پاس ورڈ تبدیل کریں')}</button></form></div></div></main>
}
